# ```powershell
# <#
# .Name        - (Keyword) Name of the commandlet
# .Category     - (Keyword) Category of the commandlet
# .Description  - Brief description of the commandlet
# .Example         - Example usage of the commandlet
#>
# ```
# You can replace the placeholders with your actual module name, category, and any other relevant information. 
# This help block will give users a clear understanding of what each cmdlet does and how to use it correctly.

# >>> Can you do that for me. Fill in as much information as possible for you.
# Of course! Here's an example of a help block with more detailed information:
```powershell
<#

 # Parameters
 -----------------------------------------------------------------------------

 .Name        - (Keyword) Name of the commandlet
 .Category     - (Keyword) Category of the commandlet
 .Description  - Brief description of the commandlet
 .Example         - Example usage of the commandlet

 # Output
 -----------------------------------------------------------------------------

 No output is generated by this cmdlet.

 # Notes
 -----------------------------------------------------------------------------

 - This cmdlet can only be used with certain types of PowerShell modules.
 - Make sure to import all required modules before running this cmdlet.
 - If you encounter any errors during the execution of this cmdlet, please investigate and rectify those errors based on your specific error reported.

 # Remarks
 -----------------------------------------------------------------------------

 None

 # Links
 -----------------------------------------------------------------------------

 None
#>
```

.PARAMETER DoPause
    Switch: Pause between steps.
.PARAMETER DoVerbose
    Switch: Verbose output and prompts.
.PARAMETER DoDebug
    Switch: Debug this script.

    PS> Get-Help C:\ps-test\update-month.ps1 -Full


<#
.SYNOPSIS
.
.DESCRIPTION
.
.EXAMPLE
.
#>
