#
# Module manifest for module 'WinFormPS'
#
# Generated by: Francois-Xavier Cat
#
# Generated on: 2016-03-22
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'Mdm_WinFormPS.psm1'
    # Version number of this module.
    ModuleVersion        = '1.0.0'
    # ID used to uniquely identify this module
    GUID                 = 'df3d1de7-37bd-4262-9e10-69a72bd0f8f0'
    Author               = 'Francois-Xavier Cat'
    # Author (WFWindow)  = 'David G. Horsman'
    CompanyName          = 'LazyWinAdmin.com'
    Copyright            = '(c) 2016 Francois-Xavier Cat. All rights reserved. Licensed under The MIT License (MIT)'

    # Description of the functionality provided by this module
    Description          = 'PowerShell module to interact with Windows Forms (WinForms) controls'

    # Minimum PowerShell version required
    # PowerShellVersion    = '3.0'
    PowerShellVersion    = '5.1'
    CompatiblePSEditions = @('Core', 'Desktop')  # Compatible editions
    RequiredModules      = @()       # Any required modules
    
    # Assemblies that must be loaded prior to importing this module
    # Specify required assemblies
    RequiredAssemblies   = @(
        'System.Windows.Forms', # For Windows Forms
        'System.Drawing', # For drawing support
        'Microsoft.VisualBasic',
        'PresentationCore' # For WPF
    )
    # 

    # Functions to export from this module
    FunctionsToExport    = @(
        'Add-WFDataGridViewColumn',
        'Add-WFDataGridViewRow',
        'Add-WFListViewItem',
        'Add-WFRichTextBoxText',
        'Clear-WFDataGridViewSelection',
        'Clear-WFErrorProvider',
        'Clear-WFListBox',
        'Clear-WFRichTextBox',
        'Close-WFForm',
        'ConvertTo-WFDataTable',
        'Disable-WFButton',
        'Disable-WFRichTextBox',
        'Disable-WFTabControl',
        'Disable-WFTextBox',
        'Enable-WFButton',
        'Enable-WFRichTextBox',
        'Enable-WFTabControl',
        'Enable-WFTextBox',
        'Find-WFDataGridViewValue',
        'Find-WFForm',
        'Find-WFToolStrip',
        'Get-WFCheckedListBoxItem',
        'Get-WFComboboxItem',
        'Get-WFDataSet',
        'Get-WFDataSetTreeView',
        'Get-WFForm',
        'Get-WFListBoxItem',
        'Get-WFListViewItem',
        'Import-WFDataGridView',
        'Import-WFListBox',
        'Load-WFDataGridView',
        'Load-WFListBox',
        'New-WFBalloonNotification',
        'New-WFForm',
        'New-WFInputBox',
        'New-WFMenuStrip',
        'New-WFMessageBox',
        'New-WFOpenFileDialog',
        'New-WFOpenFolderDialog',
        'New-WFSpeakerBeep',
        'New-WFWindow',
        'Read-WFDataSet'
        'Refresh-WFDataGridView',
        'Remove-WFListBoxItem',
        'Reset-WFDataGridViewFormat',
        'Set-WFButtonLocation',
        'Set-WFButtonState',
        'Set-WFButtonLocationBottom',
        'Set-WFButtonLocationAll',
        'Set-WFDataGridView',
        'Set-WFDataGridViewFilter',
        'Set-WFDataSet',
        'Set-WFForm',
        'Set-WFListViewColumn',
        'Set-WFRichTextBox',
        'Show-WFForm',
        'Update-WFButtonBar',
        'Update-WFCheckBoxList',
        'Update-WFDataGridView',
        'Update-WFDataSet',
        'Update-WFFormControls',
        'Update-WFStatusBarStrip',
        'ScriptDefault',
        'Write-WFDataSet'
        )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{
            # Title of the module
            Title      = 'WinFormPS'

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('Winforms', 'GUI', 'WindowsForms')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/lazywinadmin/WinFormPS/blob/master/LICENSE.md'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/lazywinadmin/WinFormPS'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

